jake_helper :version do
  "0.5.0"
end

FILES = []

jake_hook :file_created do |package, build, path|
  FILES << File.basename(path)
end

jake_hook :build_complete do |build|
  write = lambda do |file, content|
    File.open(File.join(build.build_dir, file), 'w') { |f| f.write(content) }
  end
  write['README', 'Should be generated after build']
  write['LISTING', FILES.sort * "\n"]
end

