jake_helper :version do
  "0.5.0"
end

FILES = []
DEPS  = {}

jake_hook :file_created do |build, package, build_type, path|
  FILES << File.basename(path)
  DEPS[path] = package.meta if build_type == :min
end

jake_hook :build_complete do |build|
  write = lambda do |file, content|
    File.open(File.join(build.build_dir, file), 'w') { |f| f.write(content) }
  end
  write['README', 'Should be generated after build']
  write['LISTING', FILES.sort * "\n"]
  
  write['packages.js', ERB.new(File.read('packages.erb')).result(binding)]
end

